export const data = {
  name: "Nagarjun H",
  headline: "Software Engineer specializing in AI, Cloud, and Web Development.",
  contact: {
    email: "nagarjunh77@gmail.com",
    phone: "+91 8431426691",
    linkedin: "https://linkedin.com/in/Nagarjun-H/",
    github: "https://github.com/Nagarjun-07",
    location: "Mysore, Karnataka, India",
  },
  education: [
    {
      degree: "BE in Information Science - 8.5 CGPA",
      institution: "PES College Of Engineering",
      duration: "Dec 2021 – Jul 2025",
      description: "Focus on Data Structures, Algorithms, Machine Learning, and Web Development.",
    },
    {
      degree: "Sadvidya Composite PU",
      institution: "PCMB - 96.67% | SSLC - 96.48%",
      duration: "Jun 2019 – Aug 2021",
      description: "Pre-University education with a focus on Physics, Chemistry, Mathematics, and Biology.",
    },
  ],
  experience: [
    {
      role: "SWE Fellowship",
      company: "Headstarter AI",
      duration: "Jun 2024 – Aug 2024",
      location: "New York, United States (Remote)",
      description: [
        "Built and deployed 4 AI projects in 5 weeks using React JS, Firebase, Clerk, and Vercel, following agile methodologies.",
        "Led a team of 3 to develop an interactive customer support agent using Next.js and a custom RAG pipeline with OpenAI.",
        "Collaborated to build a SaaS product for generating dynamic flashcards using Llama 3.1 via the Groq API, integrating Stripe for payments.",
        "Scaled 2 web-apps to 100+ users, iterating on user feedback for continuous optimizations.",
      ],
    },
  ],
  projects: [
    {
      title: "AI Powered Flashcard SaaS",
      tech: ["Clerk", "Firebase", "Next.Js", "OpenAI", "Stripe API"],
      date: "July 2024",
      description: "Built a SaaS platform with React.js and Next.js, offering secure authentication and payment processing via Stripe. Implemented AI-powered flashcard generation using the OpenAI API.",
      image: "https://placehold.co/600x400.png",
      aiHint: "education technology",
      link: "#",
    },
    {
      title: "Storm Scout",
      tech: ["Flask", "OpenWeatherMap API", "Google Maps API"],
      date: "April 2024",
      description: "Developed a Flask based web application that provides real-time weather updates and travel weather information, with an interface to enter start and end locations.",
      image: "https://placehold.co/600x400.png",
      aiHint: "weather map",
      link: "#",
    },
    {
      title: "Snack Snap Pantry Tracker",
      tech: ["Next.Js", "Firebase", "Google Analytics", "Vercel"],
      date: "June 2024",
      description: "A dynamic web application using Next.js for managing pantry items, featuring full CRUD operations and integrated Google Analytics for user interaction tracking.",
      image: "https://placehold.co/600x400.png",
      aiHint: "inventory management",
      link: "#",
    },
  ],
  skills: {
    languages: ["Java", "Python (OOP)", "HTML", "CSS", "C"],
    frameworks_technologies: ["React.Js", "Next.Js", "Flask", "Machine learning"],
    databases: ["MySQL", "Firestore/Firebase", "Pinecone"],
    apis_tools: ["OpenAI", "Stripe", "Clerk", "OpenWeather", "Google Maps API", "Google Analytics", "Git", "GitHub", "VScode", "Vercel", "Canva", "Figma", "Google Sheets", "MS Word"],
    soft_skills: ["Communication", "Problem solving", "Collaboration", "Adaptability", "Networking"],
  },
  certifications: [
    "Google AI Essentials certified from Cousera",
    "Zscaler cloud security – Eduskills",
    "Cybersecurity and its fundamentals – Zscaler",
  ],
};
