export const data = {
  name: "Nagarjun H",
  headline: "Software Engineer specializing in AI, Cloud, and Web Development.",
  contact: {
    email: "nagarjunh77@gmail.com",
    phone: "+91 8431426691",
    linkedin: "https://linkedin.com/in/Nagarjun-H/",
    github: "https://github.com/Nagarjun-07",
    location: "Mysore, Karnataka, India",
  },
  education: [
    {
      degree: "Focus on Machine Learning & Data Structures",
      institution: "Self-study & Project-based Learning",
      duration: "Ongoing",
      description: "Continuous learning through online courses, personal projects, and fellowships.",
    },
  ],
  experience: [
    {
      role: "SWE Fellowship",
      company: "Headstarter AI",
      duration: "Jun 2024 – Aug 2024",
      location: "New York, United States (Remote)",
      description: [
        "Built and deployed 4 AI projects in 5 weeks using React JS, Firebase, Clerk, and Vercel, following agile methodologies.",
        "Led a team of 3 to develop an interactive customer support agent using Next.js and a custom RAG pipeline with OpenAI.",
        "Collaborated to build a SaaS product for generating dynamic flashcards using Llama 3.1 via the Groq API, integrating Stripe for payments.",
        "Scaled 2 web-apps to 100+ users, iterating on user feedback for continuous optimizations.",
      ],
    },
  ],
  projects: [
    {
      title: "AI Powered Flashcard SaaS",
      tech: ["Clerk", "Firebase", "Next.Js", "OpenAI", "Stripe API"],
      date: "July 2024",
      description: "A SaaS platform with React.js and Next.js, offering secure authentication, Stripe payments, and AI-powered flashcard generation.",
      image: "https://placehold.co/600x400.png",
      aiHint: "education technology",
      link: "#",
    },
    {
      title: "SkinVal 2.0",
      tech: ["Web Scraping", "RAG", "AI"],
      date: "Ongoing",
      description: "A skincare product recommending website that provides skin condition detection and personalized product recommendations using advanced web scraping and RAG.",
      image: "https://placehold.co/600x400.png",
      aiHint: "skincare beauty",
      link: "https://skinval.vercel.app",
      github: "#",
    },
    {
      title: "Dolphin Doc Extractor",
      tech: ["Next.js", "Genkit AI", "Vercel"],
      date: "Ongoing",
      description: "An AI-powered web application to intelligently extract structured and unstructured data from uploaded PDF documents, allowing users to ask context-aware questions.",
      image: "https://placehold.co/600x400.png",
      aiHint: "document analysis",
      link: "https://dolphin-doc-extractor.vercel.app/",
      github: "#",
    },
    {
      title: "Storm Scout",
      tech: ["Flask", "OpenWeatherMap API", "Google Maps API"],
      date: "April 2024",
      description: "A Flask web application providing real-time weather updates, travel weather information, and activity suggestions, with features to display weather along travel routes.",
      image: "https://placehold.co/600x400.png",
      aiHint: "weather map",
      link: "#",
    },
     {
      title: "Snack Snap Pantry Tracker",
      tech: ["Next.Js", "Firebase", "Google Analytics", "Vercel"],
      date: "June 2024",
      description: "A dynamic web application for managing pantry items, featuring full CRUD operations, and integrated Google Analytics for user interaction tracking.",
      image: "https://placehold.co/600x400.png",
      aiHint: "inventory management",
      link: "#",
    },
    {
      title: "AutismNetX Screening",
      tech: ["Deep Learning", "Neural Networks"],
      date: "Ongoing",
      description: "This project leverages advanced neural networks to analyze behavioral and developmental data, aiming to provide faster, more accessible, and accurate preliminary screening for autism.",
      image: "https://placehold.co/600x400.png",
      aiHint: "neural network",
      link: "#",
    },
  ],
  skills: {
    languages: ["Java", "Python (OOP)", "HTML", "CSS", "C"],
    frameworks_technologies: ["React.Js", "Next.Js", "Flask", "Machine learning"],
    databases: ["MySQL", "Firestore/Firebase", "Pinecone"],
    apis_tools: ["OpenAI", "Stripe", "Clerk", "OpenWeather", "Google Maps API", "Google Analytics", "Git", "GitHub", "Vercel", "Figma"],
  },
  certifications: [
    "Google AI Essentials certified from Cousera",
    "Zscaler cloud security – Eduskills",
    "Cybersecurity and its fundamentals – Zscaler",
    "Microsoft NLP and AI - Microsoft",
  ],
};
